# Generated by Django 3.1 on 2020-09-12 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Snippter',
            new_name='Snippet',
        ),
    ]
